CREATE TABLE SOALOG.LOG_ENTRY 
(
  LOG_ENTRY_ID NUMBER NOT NULL 
, INTEGRATION_INSTANCE_ID VARCHAR2(1000) 
, INSTANCE_VERSION VARCHAR2(50) 
, LOG_DATE DATE 
, LOG_LEVEL VARCHAR2(50) 
, LOG_MSG VARCHAR2(2000) 
, LOG_PAYLOAD VARCHAR2(2000) 
, LOG_INTERFACE_ID NUMBER 
, CONSTRAINT LOG_ENTRY_PK PRIMARY KEY 
  (
    LOG_ENTRY_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.ENTRY_VALUES 
(
  VALUE_ID NUMBER NOT NULL 
, VALUE_NAME VARCHAR2(200) 
, ENTRY_VALUE VARCHAR2(2000) 
, LOG_ENTRY_ID NUMBER 
, CONSTRAINT ENTRY_VALUES_PK PRIMARY KEY 
  (
    VALUE_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.INTERFACE_USR_GROUPS 
(
  LOG_INTERFACE_ID NUMBER NOT NULL 
, USER_GROUP_ID NUMBER NOT NULL 
, CONSTRAINT INTERFACE_USR_GROUPS_PK PRIMARY KEY 
  (
    LOG_INTERFACE_ID 
  , USER_GROUP_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.LOG_SCHED 
(
  LOG_SCHED_ID NUMBER NOT NULL 
, DAYS_OLDER_TO_REMOVE NUMBER 
, LOG_DATE DATE 
, LOG_INTERFACE_ID NUMBER 
, CONSTRAINT LOG_SCHED_PK PRIMARY KEY 
  (
    LOG_SCHED_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.LOG_FIELDS 
(
  LOG_FIELD_ID NUMBER NOT NULL 
, LOG_FIELD_NAME VARCHAR2(200) 
, ELEMENT_NAME VARCHAR2(200) 
, XML_XPATH VARCHAR2(2000) 
, LOG_INTERFACE_ID NUMBER 
, CONSTRAINT LOG_FIELDS_PK PRIMARY KEY 
  (
    LOG_FIELD_ID 
  )
  ENABLE 
);

CREATE TABLE USR_GRP_USR 
(
  USR_GRP_USR_ID NUMBER NOT NULL 
, INT_USR_ID NUMBER 
, USER_GROUP_ID NUMBER NOT NULL 
, EXT_USRNAME VARCHAR2(100) 
, CONSTRAINT USR_GRP_USR_PK PRIMARY KEY 
  (
    USR_GRP_USR_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.INT_USR 
(
  INT_USR_ID NUMBER NOT NULL 
, USR_NAME VARCHAR2(50) 
, USR_PWORD VARCHAR2(100) 
, USR_DESC VARCHAR2(20) 
, CONSTRAINT INT_USR_PK PRIMARY KEY 
  (
    INT_USR_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.LOGINTERFACE_NOTIFICATION 
(
  LOG_INTERFACE_NOTIFICATION_ID NUMBER NOT NULL 
, RECIPIENT_EMAIL VARCHAR2(200) 
, NOTIFICATION_DESC VARCHAR2(1000) 
, INTERFACE_ENV VARCHAR2(20) 
, LOG_INTERFACE_ID NUMBER 
, CONSTRAINT LOGINTERFACE_NOTIFICATION_PK PRIMARY KEY 
  (
    LOG_INTERFACE_NOTIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.USER_GROUP 
(
  USER_GROUP_ID NUMBER NOT NULL 
, USER_GROUP_NAME VARCHAR2(50) NOT NULL 
, USER_GROUP_DETAILS VARCHAR2(200) 
, CONSTRAINT USER_GROUP_PK PRIMARY KEY 
  (
    USER_GROUP_ID 
  )
  ENABLE 
);

CREATE TABLE SOALOG.LOG_INTERFACE 
(
  LOG_INTERFACE_ID NUMBER NOT NULL 
, LOG_INTERFACE_NAME VARCHAR2(1000) NOT NULL 
, LOG_INTERFACE_VERSION VARCHAR2(20) NOT NULL 
, LOG_MESSAGE_FLAG VARCHAR2(1) NOT NULL 
, PREFERRED_LOGGING_LEVEL VARCHAR2(20) 
, MSG_MAX_LENGHT NUMBER 
, ENVIRONMENT_FLAG VARCHAR2(20) NOT NULL 
, INTEGRATION_TYPE VARCHAR2(20) 
, MSG_ENCODING VARCHAR2(20) 
, APPLY_BASE64 VARCHAR2(1) 
, CONSTRAINT LOG_INTERFACE_PK PRIMARY KEY 
  (
    LOG_INTERFACE_ID 
  )
  ENABLE 
);

ALTER TABLE SOALOG.LOG_ENTRY
ADD CONSTRAINT LOG_ENTRY_LOG_INTERFACE_FK FOREIGN KEY
(
  LOG_INTERFACE_ID 
)
REFERENCES SOALOG.LOG_INTERFACE
(
  LOG_INTERFACE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.ENTRY_VALUES
ADD CONSTRAINT ENTRY_VALUES_LOG_ENTRY_FK FOREIGN KEY
(
  LOG_ENTRY_ID 
)
REFERENCES SOALOG.LOG_ENTRY
(
  LOG_ENTRY_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.INTERFACE_USR_GROUPS
ADD CONSTRAINT INTERFACE_USR_GROUPS_FK FOREIGN KEY
(
  LOG_INTERFACE_ID 
)
REFERENCES SOALOG.LOG_INTERFACE
(
  LOG_INTERFACE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.INTERFACE_USR_GROUPS
ADD CONSTRAINT INTERFACE_USR_GROUPS_FK1 FOREIGN KEY
(
  USER_GROUP_ID 
)
REFERENCES SOALOG.USER_GROUP
(
  USER_GROUP_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.LOG_SCHED
ADD CONSTRAINT LOG_SCHED_LOG_INTERFACE_FK FOREIGN KEY
(
  LOG_INTERFACE_ID 
)
REFERENCES SOALOG.LOG_INTERFACE
(
  LOG_INTERFACE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.LOG_FIELDS
ADD CONSTRAINT LOG_FIELDS_LOG_INTERFACE_FK FOREIGN KEY
(
  LOG_INTERFACE_ID 
)
REFERENCES SOALOG.LOG_INTERFACE
(
  LOG_INTERFACE_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USR_GRP_USR
ADD CONSTRAINT USR_GRP_USR_INT_USR_FK FOREIGN KEY
(
  INT_USR_ID 
)
REFERENCES SOALOG.INT_USR
(
  INT_USR_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USR_GRP_USR
ADD CONSTRAINT USR_GRP_USR_USER_GROUP_FK FOREIGN KEY
(
  USER_GROUP_ID 
)
REFERENCES SOALOG.USER_GROUP
(
  USER_GROUP_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE SOALOG.LOGINTERFACE_NOTIFICATION
ADD CONSTRAINT LOGINTERFACE_NOTIFICATION_FK FOREIGN KEY
(
  LOG_INTERFACE_ID 
)
REFERENCES SOALOG.LOG_INTERFACE
(
  LOG_INTERFACE_ID 
)
ON DELETE CASCADE ENABLE;
