package stockmann.com.soalogger.ws.client;

import javax.xml.ws.WebFault;

@WebFault(faultBean="stockmann.com.soalogger.ws.client.types.Exception",
  targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
  name="Exception")
public class Exception
  extends java.lang.Exception
{
  private stockmann.com.soalogger.ws.client.types.Exception faultInfo;

  public Exception(String message,
                   stockmann.com.soalogger.ws.client.types.Exception faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Exception(String message,
                   stockmann.com.soalogger.ws.client.types.Exception faultInfo,
                   Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public stockmann.com.soalogger.ws.client.types.Exception getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(stockmann.com.soalogger.ws.client.types.Exception faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)
