package stockmann.com.soalogger.ws.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import stockmann.com.soalogger.ws.client.Exception;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://hiphiphurax:8080/SoaloggerService/SoaloggerServiceService?WSDL",
  targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
  name="SoaloggerService")
@XmlSeeAlso(
  { stockmann.com.soalogger.ws.client.types.ObjectFactory.class })
public interface SoaloggerService
{
  @WebMethod
  @Action(input="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogEntryValuesRequest", fault =
      { @FaultAction(value="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogEntryValues/Fault/Exception",
          className = Exception.class) }, output="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogEntryValuesResponse")
  @ResponseWrapper(localName="addLogEntryValuesResponse", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogEntryValuesResponse")
  @RequestWrapper(localName="addLogEntryValues", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogEntryValues")
  @WebResult(targetNamespace="")
  public int addLogEntryValues(@WebParam(targetNamespace="", name="arg0")
    List<stockmann.com.soalogger.ws.client.types.LogEntryTo> arg0)
    throws stockmann.com.soalogger.ws.client.Exception;

  @WebMethod
  @Action(input="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/getInterfaceFieldsRequest", fault =
      { @FaultAction(value="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/getInterfaceFields/Fault/Exception",
          className=stockmann.com.soalogger.ws.client.Exception.class) },
    output="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/getInterfaceFieldsResponse")
  @ResponseWrapper(localName="getInterfaceFieldsResponse",
    targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.GetInterfaceFieldsResponse")
  @RequestWrapper(localName="getInterfaceFields", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.GetInterfaceFields")
  @WebResult(targetNamespace="")
  public List<stockmann.com.soalogger.ws.client.types.LogFieldTo> getInterfaceFields(@WebParam(targetNamespace="",
      name="arg0")
    stockmann.com.soalogger.ws.client.types.LogInterfaceTo arg0)
    throws stockmann.com.soalogger.ws.client.Exception;

  @WebMethod
  @Action(input="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogInterfaceEntryRequest", fault =
      { @FaultAction(value="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogInterfaceEntry/Fault/Exception",
          className=stockmann.com.soalogger.ws.client.Exception.class) },
    output="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogInterfaceEntryResponse")
  @ResponseWrapper(localName="addLogInterfaceEntryResponse",
    targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogInterfaceEntryResponse")
  @RequestWrapper(localName="addLogInterfaceEntry", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogInterfaceEntry")
  @WebResult(targetNamespace="")
  public stockmann.com.soalogger.ws.client.types.LogInterfaceTo addLogInterfaceEntry(@WebParam(targetNamespace="",
      name="interface")
    stockmann.com.soalogger.ws.client.types.LogInterfaceTo _interface)
    throws stockmann.com.soalogger.ws.client.Exception;

  @WebMethod
  @Action(input="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogMessageRequest",
    output="http://soaloggerservice.web.logging.soa.stockmann/SoaloggerService/addLogMessageResponse")
  @ResponseWrapper(localName="addLogMessageResponse", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogMessageResponse")
  @RequestWrapper(localName="addLogMessage", targetNamespace="http://soaloggerservice.web.logging.soa.stockmann/",
    className="stockmann.com.soalogger.ws.client.types.AddLogMessage")
  @WebResult(targetNamespace="")
  public int addLogMessage(@WebParam(targetNamespace="", name="logMessage")
    stockmann.com.soalogger.ws.client.types.LogMsgTo logMessage);
}
